global class BookingRequest {
    public String firstName;
    public String lastName;
  
    public String phone;
    public String email;

    public String personalOrCorporate;
    public String occasion;
    public String eventType;
    public Date eventDate;

    public Datetime guestArrivalTime;
    public Datetime guestDepartureTime;
    public Integer numberOfGuests;
    public String venueAddress;
    public Integer numberOfStaffRequired;

    public String needExtraServices;
    public String uniformRequired;
    public String clientBrief;
    public String specialRequirements;
    public Decimal estimatedBudget;
}